spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
    url: jdbc:mysql://mysql_con:3306/sample_db
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create  # 개발 환경에서 `update` 사용, 필요시 `create`로 변경
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: redis_con
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 6000000 # 100분 동안 캐시 유지
  kafka:
    bootstrap-servers: localhost:10000, localhost:10001, localhost:10002
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: INFO
    org.apache.kafka: INFO
#    org.hibernate.orm.jdbc.bind: TRACE

